CREATE TABLE users (
  userID int primary key generated always as identity,
  userName varchar(255) NOT NULL,
  fullName varchar(255) NOT NULL,
  jobTitle varchar(255) NOT NULL,
  departmentID int(11) NOT NULL,
  userEmail varchar(255) NOT NULL,
  pwd varchar(255) NOT NULL,
  roles varchar(255) NOT NULL,
  active boolean NOT NULL,
  startDate date NOT NULL,
  endDate date NOT NULL,
  phone varchar(255) NOT NULL,
  mobilePhone varchar(255) NOT NULL,
  address varchar(55) NOT NULL,
  zipCode varchar(100) NOT NULL,
  city varchar(255) NOT NULL,
  skills text NOT NULL,
  signedContract boolean NOT NULL,
  contractID int(11) NOT NULL,
  documents varchar(255) NOT NULL,
  supervisorID int(11) NOT NULL,
  workplaceID int(11) NOT NULL,
  userComments text NOT NULL
);
